import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');
// background #cbf1f5
// primary #6387ff
// text #2b2e4a
// hover #74f9ff
// Dima Barf  - DimaBlue - IRANYekan

export default StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shape: {
    backgroundColor: '#0779e4',
    width: 200,
    height: 200,
    borderRadius: 100,
    position: 'relative',
    top: height / 6,
    right: -height / 6,
  },
  shape2: {
    backgroundColor: '#323edd',
    width: 200,
    height: 200,
    borderRadius: 100,
    position: 'relative',
    top: -height / 8,
    right: -width / 1.8,
  },
  shape3: {
    backgroundColor: '#f67280',
    width: 200,
    height: 200,
    borderRadius: 100,
    position: 'relative',
    bottom: -height / 1.7,
    left: -200,
  },
  shape4: {
    backgroundColor: '#323edd',
    width: 200,
    height: 200,
    borderRadius: 100,
    position: 'relative',
    bottom: -height / 2.8,
    left: -width / 2.8,
  },
  input: {
    width: 320,
    height: 200,
    borderColor: 'black',
    borderWidth: 0.1,
    position: 'relative',
    top: -height / 1.6,
    left: width / 18,
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    elevation: 1,
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
  },
  input_username: {
    width: 250,
    height: 50,
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  input_password: {
    width: 250,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    marginTop: 10,
  },
  input_icon: {
    fontSize: 50,
    color: 'white',
    borderRadius: 100,
    position: 'relative',
    top: -height / 6,
    right: width / 1.4,
  },
  icons: {
    fontSize: 30,
    color: '#6387ff',
  },
  textInput: {
    height: 45,
    width: 150,
    borderWidth: 0.5,
    textAlign: 'center',
    fontSize: 20,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderColor: '#f6416c',
  },

  Viewtext: {
    position: 'relative',
    top: -height / 1.4,
    left: width / 20,
    width: 300,
    height: 80,
    color: '#6387ff',
  },
  Viewtext_txt: {
    textAlign: 'center',
    color: '#ff2e63',
    fontSize: 75,
    fontFamily: 'Dima Barf',
  },
  view_bottom: {
    position: 'relative',
    top: -height / 1.8,
    right: -width / 2.7,
    width: 110,
    height: 60,
    color: '#6387ff',
    borderColor: 'black',
    borderWidth: 0.2,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1,
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    backgroundColor: '#ff2e63',
  },
  view_bottom_txt: {
    textAlign: 'center',
    fontSize: 10,
    color: 'white',
    fontFamily: 'DimaBlue',
  },
});
